inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  rubocop-rspec: config/default.yml

require:
  - rubocop-rspec

Metrics/BlockLength:
  Max: 40

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 40

RSpec/DescribedClass:
  Enabled: false
